### ISSUE TITLE
How to submit parameters?

### ISSUE THREAD

**Issue by bch80** [DennisDeSwart/php-stanford-corenlp-adapter#1]
Hey there, great job this adapter!

for a first round, I'd like to simply use those parameters for OpenNLP:

`-annotators tokenize,ssplit`

How is it possible to make this happen via the CorenlpAdapter?

**Comment by bch80** [comment]
Oh .. sorry for that one. It says so in the bootstrap.php:

`    // if you want specific annotators, you can do it like this:
    // define('CURLPROPERTIES' , '%22annotators%22%3A%22tokenize%2Cregexner%2Cparse%2Cdepparse%2Cpos%2Clemma%2Cmention%2Copenie%2Cner%2Ccoref%2Ckbp%22%2C%22prettyPrint%22%3A%22true%22');
`

**Comment by DennisDeSwart** [comment]
Hi Chris8080,

Yes, you can change them in "bootstrap.php". As you can see, it's not easy to edit, I wanted to make that a bit more user friendly.  But it works. Don't remove the bits at the end. Try something like this:

`define('CURLPROPERTIES' , '%22annotators%22%3A%22tokenize%2Cparse%2Cdepparse%22%2C%22prettyPrint%22%3A%22true%22');`

**Comment by ghost** [comment]
FYI, this doesn't seem to work. For example, I tried 

define('CURLPROPERTIES' , '%22annotators%22%3A%22ner%22%2C%22prettyPrint%22%3A%22true%22');

And the server still runs it with full annotators.
