### ISSUE TITLE
Error composer update （windows 10）

### ISSUE THREAD

**Issue by sangyao** [DennisDeSwart/php-stanford-corenlp-adapter#2]
Hello Mr. Swart

there ist a problem, wenn i enter "composer update"，

> Root package 'dennis-de-swart/php-stanford-corenlp-adapter' cannot require itself in its composer.json
> Did you accidentally name your root package after an external package?

How can i Solve this problem.

thank you very much 

yao

**Comment by DennisDeSwart** [comment]
Hi yao,

Do you need help?

Greetings,
Dennis

**Comment by sangyao** [comment]
hello, 

Thank you for your response， this problem has been solved.

Greetings

Yao
